const books = [
  {
    abbrev: {
      pt: 'gn',
      en: 'gn',
    },
    author: 'Moisés',
    chapters: 50,
    group: 'Pentateuco',
    name: 'Gênesis',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'ex',
      en: 'ex',
    },
    author: 'Moisés',
    chapters: 40,
    group: 'Pentateuco',
    name: 'Êxodo',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'lv',
      en: 'lv',
    },
    author: 'Moisés',
    chapters: 27,
    group: 'Pentateuco',
    name: 'Levítico',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'nm',
      en: 'nm',
    },
    author: 'Moisés',
    chapters: 36,
    group: 'Pentateuco',
    name: 'Números',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'dt',
      en: 'dt',
    },
    author: 'Moisés',
    chapters: 34,
    group: 'Pentateuco',
    name: 'Deuteronômio',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'js',
      en: 'js',
    },
    author: 'Josué',
    chapters: 24,
    group: 'Históricos',
    name: 'Josué',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'jz',
      en: 'jud',
    },
    author: 'Samuel',
    chapters: 21,
    group: 'Históricos',
    name: 'Juízes',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'rt',
      en: 'rt',
    },
    author: 'Samuel',
    chapters: 4,
    group: 'Históricos',
    name: 'Rute',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: '1sm',
      en: '1sm',
    },
    author: 'Samuel',
    chapters: 31,
    group: 'Históricos',
    name: '1º Samuel',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: '2sm',
      en: '2sm',
    },
    author: 'Samuel',
    chapters: 24,
    group: 'Históricos',
    name: '2º Samuel',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: '1rs',
      en: '1kgs',
    },
    author: 'Jeremias',
    chapters: 22,
    group: 'Históricos',
    name: '1º Reis',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: '2rs',
      en: '2kgs',
    },
    author: 'Jeremias',
    chapters: 25,
    group: 'Históricos',
    name: '2º Reis',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: '1cr',
      en: '1ch',
    },
    author: 'Esdras',
    chapters: 29,
    group: 'Históricos',
    name: '1º Crônicas',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: '2cr',
      en: '2ch',
    },
    author: 'Esdras',
    chapters: 36,
    group: 'Históricos',
    name: '2º Crônicas',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'ed',
      en: 'ezr',
    },
    author: 'Esdras',
    chapters: 10,
    group: 'Históricos',
    name: 'Esdras',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'ne',
      en: 'ne',
    },
    author: 'Neemias',
    chapters: 13,
    group: 'Históricos',
    name: 'Neemias',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'et',
      en: 'et',
    },
    author: 'Desconhecido',
    chapters: 10,
    group: 'Históricos',
    name: 'Ester',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'job',
      en: 'job',
    },
    author: 'Desconhecido',
    chapters: 42,
    group: 'Poéticos',
    name: 'Jó',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'sl',
      en: 'ps',
    },
    author: 'David, Moisés, Salomão',
    chapters: 150,
    group: 'Poéticos',
    name: 'Salmos',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'pv',
      en: 'prv',
    },
    author: 'Salomão',
    chapters: 31,
    group: 'Poéticos',
    name: 'Provérbios',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'ec',
      en: 'ec',
    },
    author: 'Salomão',
    chapters: 12,
    group: 'Poéticos',
    name: 'Eclesiastes',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'ct',
      en: 'so',
    },
    author: 'Salomão',
    chapters: 8,
    group: 'Poéticos',
    name: 'Cânticos',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'is',
      en: 'is',
    },
    author: 'Isaías',
    chapters: 66,
    group: 'Profetas maiores',
    name: 'Isaías',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'jr',
      en: 'jr',
    },
    author: 'Jeremias',
    chapters: 52,
    group: 'Profetas maiores',
    name: 'Jeremias',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'lm',
      en: 'lm',
    },
    author: 'Jeremias',
    chapters: 5,
    group: 'Profetas maiores',
    name: 'Lamentações de Jeremias',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'ez',
      en: 'ez',
    },
    author: 'Ezequiel',
    chapters: 48,
    group: 'Profetas maiores',
    name: 'Ezequiel',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'dn',
      en: 'dn',
    },
    author: 'Daniel',
    chapters: 12,
    group: 'Profetas maiores',
    name: 'Daniel',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'os',
      en: 'ho',
    },
    author: 'Oséias',
    chapters: 14,
    group: 'Profetas menores',
    name: 'Oséias',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'jl',
      en: 'jl',
    },
    author: 'Joel',
    chapters: 3,
    group: 'Profetas menores',
    name: 'Joel',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'am',
      en: 'am',
    },
    author: 'Amós',
    chapters: 9,
    group: 'Profetas menores',
    name: 'Amós',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'ob',
      en: 'ob',
    },
    author: 'Obadias',
    chapters: 1,
    group: 'Profetas menores',
    name: 'Obadias',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'jn',
      en: 'jn',
    },
    author: 'Jonas',
    chapters: 4,
    group: 'Profetas menores',
    name: 'Jonas',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'mq',
      en: 'mi',
    },
    author: 'Miquéias',
    chapters: 7,
    group: 'Profetas menores',
    name: 'Miquéias',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'na',
      en: 'na',
    },
    author: 'Naum',
    chapters: 3,
    group: 'Profetas menores',
    name: 'Naum',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'hc',
      en: 'hk',
    },
    author: 'Habacuque',
    chapters: 3,
    group: 'Profetas menores',
    name: 'Habacuque',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'sf',
      en: 'zp',
    },
    author: 'Sofonias',
    chapters: 3,
    group: 'Profetas menores',
    name: 'Sofonias',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'ag',
      en: 'hg',
    },
    author: 'Ageu',
    chapters: 2,
    group: 'Profetas menores',
    name: 'Ageu',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'zc',
      en: 'zc',
    },
    author: 'Zacarias',
    chapters: 14,
    group: 'Profetas menores',
    name: 'Zacarias',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'ml',
      en: 'ml',
    },
    author: 'Malaquias',
    chapters: 4,
    group: 'Profetas menores',
    name: 'Malaquias',
    testament: 'VT',
  },
  {
    abbrev: {
      pt: 'mt',
      en: 'mt',
    },
    author: 'Mateus',
    chapters: 28,
    group: 'Evangelhos',
    name: 'Mateus',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: 'mc',
      en: 'mk',
    },
    author: 'Marcos',
    chapters: 16,
    group: 'Evangelhos',
    name: 'Marcos',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: 'lc',
      en: 'lk',
    },
    author: 'Lucas',
    chapters: 24,
    group: 'Evangelhos',
    name: 'Lucas',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: 'jo',
      en: 'jo',
    },
    author: 'João',
    chapters: 21,
    group: 'Evangelhos',
    name: 'João',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: 'at',
      en: 'act',
    },
    author: 'Lucas',
    chapters: 28,
    group: 'Histórico',
    name: 'Atos',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: 'rm',
      en: 'rm',
    },
    author: 'Paulo',
    chapters: 16,
    group: 'Cartas',
    name: 'Romanos',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: '1co',
      en: '1co',
    },
    author: 'Paulo',
    chapters: 16,
    group: 'Cartas',
    name: '1ª Coríntios',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: '2co',
      en: '2co',
    },
    author: 'Paulo',
    chapters: 13,
    group: 'Cartas',
    name: '2ª Coríntios',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: 'gl',
      en: 'gl',
    },
    author: 'Paulo',
    chapters: 6,
    group: 'Cartas',
    name: 'Gálatas',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: 'ef',
      en: 'eph',
    },
    author: 'Paulo',
    chapters: 6,
    group: 'Cartas',
    name: 'Efésios',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: 'fp',
      en: 'ph',
    },
    author: 'Paulo',
    chapters: 4,
    group: 'Cartas',
    name: 'Filipenses',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: 'cl',
      en: 'cl',
    },
    author: 'Paulo',
    chapters: 4,
    group: 'Cartas',
    name: 'Colossenses',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: '1ts',
      en: '1ts',
    },
    author: 'Paulo',
    chapters: 5,
    group: 'Cartas',
    name: '1ª Tessalonicenses',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: '2ts',
      en: '2ts',
    },
    author: 'Paulo',
    chapters: 3,
    group: 'Cartas',
    name: '2ª Tessalonicenses',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: '1tm',
      en: '1tm',
    },
    author: 'Paulo',
    chapters: 6,
    group: 'Cartas',
    name: '1ª Timóteo',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: '2tm',
      en: '2tm',
    },
    author: 'Paulo',
    chapters: 4,
    group: 'Cartas',
    name: '2ª Timóteo',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: 'tt',
      en: 'tt',
    },
    author: 'Paulo',
    chapters: 3,
    group: 'Cartas',
    name: 'Tito',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: 'fm',
      en: 'phm',
    },
    author: 'Paulo',
    chapters: 1,
    group: 'Cartas',
    name: 'Filemom',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: 'hb',
      en: 'hb',
    },
    author: 'Desconhecido',
    chapters: 13,
    group: 'Cartas',
    name: 'Hebreus',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: 'tg',
      en: 'jm',
    },
    author: 'Tiago',
    chapters: 5,
    group: 'Cartas',
    name: 'Tiago',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: '1pe',
      en: '1pe',
    },
    author: 'Pedro',
    chapters: 5,
    group: 'Cartas',
    name: '1ª Pedro',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: '2pe',
      en: '2pe',
    },
    author: 'Pedro',
    chapters: 3,
    group: 'Cartas',
    name: '2ª Pedro',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: '1jo',
      en: '1jo',
    },
    author: 'João',
    chapters: 5,
    group: 'Cartas',
    name: '1ª João',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: '2jo',
      en: '2jo',
    },
    author: 'João',
    chapters: 1,
    group: 'Cartas',
    name: '2ª João',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: '3jo',
      en: '3jo',
    },
    author: 'João',
    chapters: 1,
    group: 'Cartas',
    name: '3ª João',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: 'jd',
      en: 'jd',
    },
    author: 'Judas',
    chapters: 1,
    group: 'Cartas',
    name: 'Judas',
    testament: 'NT',
  },
  {
    abbrev: {
      pt: 'ap',
      en: 're',
    },
    author: 'João',
    chapters: 22,
    group: 'Revelações',
    name: 'Apocalipse',
    testament: 'NT',
  },
];

export default books;
